In [152]:
import numpy as np
class Perceptron(object):
    """
    eta:学习率
    n_iter：学习次数
    w_:权重
    """
    def __init__(self,eta=0.1,n_iter=20):
       self.eta=eta
       self.n_iter = n_iter
       pass
    """
    X 输入向量
    y 分类
    """
    def fit(self,X,y):
        '初始化权重向量为0，前面加一列原因是把b也看成一个权重分量'
        self.w_=np.zeros(1 + X.shape[1])
        self.errors_ = []

        for _ in range(self.n_iter):
            errors=0
            print(self.w_)
            for xi,target in zip(X,y):
                update  = self.eta*(target - self.predict(xi))
                self.w_[1:] +=update * xi
                self.w_[0]+= update
                errors += int(update!=0.0)
                self.errors_.append(errors)
                pass
            pass        
        pass
    def net_input(self,X):
        return np.dot(X,self.w_[1:])+self.w_[0]
        pass
    def predict(self,X):
        # print(np.where(self.net_input(X) >= 0.0, 1, -1))
        return np.where(self.net_input(X) >= 0.0, 1, -1)
        pass
    pass

In [153]:
file = "D:\workspace\python_workspace\deepleaning\data\iris.data.csv"
import pandas as pd
df = pd.read_csv(file,header=None)

In [154]:
import matplotlib.pyplot as plt
y=df[4].values
y=np.where(y=="Iris-setosa",-1,1)
X=df[[0,2]].values

p = Perceptron()
p.fit(X,y)
print(p.w_)
print(p.errors_)

[0. 0. 0.]
[ 20.   125.42  97.92]
[ 30.  200.6 181.4]
[ 40.   275.78 264.88]
[ 50.   350.96 348.36]
[ 60.   426.14 431.84]
[ 70.   501.32 515.32]
[ 80.  576.5 598.8]
[ 90.   651.68 682.28]
[100.   726.86 765.76]
[110.   802.04 849.24]
[120.   877.22 932.72]
[ 130.   952.4 1016.2]
[ 140.   1027.58 1099.68]
[ 150.   1102.76 1183.16]
[ 160.   1177.94 1266.64]
[ 170.   1253.12 1350.12]
[ 180.  1328.3 1433.6]
[ 190.   1403.48 1517.08]
[ 200.   1478.66 1600.56]
[ 210.   1553.84 1684.04]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 1