# Numpy 学习

In [3]:
import  numpy as np  # 导入numpy包

# 创建矩阵

In [54]:
# np.array([1,2,3]) #一维数组
# np.array([[1,2,3],[1,2,3]],dtype=np.float32)  #二维数组 ，指定数据类型为 np.float32
# np.array([1,2,3,4,5], ndmin=3)    #指定生成数组的最小维度
# np.empty([3,2], dtype=np.float32) #创建空矩阵
# np.eye(4) #生成对角线为1的矩阵
# np.zeros([2,4],dtype=np.float32)  #生成0矩阵
# np.ones([2,3],dtype=np.float32)   #生成1矩阵
# np.asarray(np.ones([2,3]))    #拷贝矩阵
# np.arange(10,20,step=2,dtype=np.float32)  #生成[10,20)区间，步长为2的数组


# 矩阵属性

In [75]:
a=np.array([[1,2,5,7],[2,54,6,7]])
# a.shape  #矩阵行列数
# a.reshape(2,-1)   #重置矩阵行列
# a.ndim    #矩阵行数
# a.size  #矩阵元素的总个数

# 矩阵运算

In [10]:
a = np.arange(3, dtype = np.float_).reshape(1,3)  
print ('第一个数组：')
print (a)
print ('\n')
print ('第二个数组：')
b = np.array([[10,10,10],[10,10,10],[10,10,10]])  
print (b)
# print ('\n')
# print ('两个数组相加：')
# print (np.add(a,b))
# print ('\n')
# print ('两个数组相减：')
# print (np.subtract(a,b))
# print ('\n')
print ('两个数组相乘：')
print (np.multiply(a,b))
print ('\n')
# print ('两个数组相除：')
# print (np.divide(a,b))
print(a.dot(b))
print ('\n')
# print(np.dot(a,b))
# print ('\n')
# print(np.dot(b,a))
# print ('\n')
# print(np.matmul(a,b))
# print ('\n')
# print(np.multiply(a,b))


第一个数组：
[[0. 1. 2.]]


第二个数组：
[10 10 10]
两个数组相乘：
[[ 0. 10. 20.]]


[30.]




In [ ]:
type(a)

In [6]:
b=np.ones(4)
b

array([1., 1., 1., 1.])

In [ ]:
a*b

In [ ]:
a+1000

In [7]:
c=np.subtract(a,b)
c

array([[ 0., -1., -1., -1.],
       [-1.,  0., -1., -1.],
       [-1., -1.,  0., -1.],
       [-1., -1., -1.,  0.]])

In [8]:
a.dot(c)

array([[ 0., -1., -1., -1.],
       [-1.,  0., -1., -1.],
       [-1., -1.,  0., -1.],
       [-1., -1., -1.,  0.]])

In [17]:
a=np.array([[1,2,3],[3,4,5],[7,8,9]])
b=np.array([[1]])
a+b

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [ ]:
np.pi

In [ ]:
a

In [ ]:
a.ndim

In [ ]:
a.shape


In [ ]:
a.size

In [ ]:
a.itemsize

In [ ]:
a.data

In [ ]:
a.dtype

In [ ]:
a[1:2,1:2]=7.8

In [ ]:
a

In [ ]:
a[1:2,2:3]

In [ ]:
dir(np.ndarray)

In [ ]:
np.arange(10,20,0.0000001).size