In [6]:
import tensorflow as tf

tensorflow_version = tf.__version__
gpu_available = tf.test.is_gpu_available()

print("tensorflow version:", tensorflow_version, "\t GPU available:", gpu_available)

a = tf.constant([1.0, 2.0], name="a")
b = tf.constant([1.0, 2.0], name="b")
result = tf.add(a, b, name="add")
print(result)


tensorflow version: 2.1.0 	 GPU available: False
tf.Tensor([2. 4.], shape=(2,), dtype=float32)


In [7]:
tf.__file__
# dir(tf)

'D:\\Anaconda3\\envs\\TF21\\lib\\site-packages\\tensorflow\\__init__.py'

In [13]:
# tf.constant([1, 2, 3, 4, 5, 6]) 
con=tf.constant(100, dtype=tf.float32)
w = tf.Variable(con)
print(w)
w.assign_sub(10) 
print(w)
lr = 0.1
epoch = 400

for epoch in range(epoch):  # for epoch 定义顶层循环，表示对数据集循环epoch次，此例数据集数据仅有1个w,初始化时候constant赋值为5，循环40次迭代。
    with tf.GradientTape() as tape:  # with结构到grads框起了梯度的计算过程。
        loss = tf.square(w + 1)
    grads = tape.gradient(loss, w)  # .gradient函数告知谁对谁求导

    w.assign_sub(lr * grads)  # .assign_sub 对变量做自减 即：w -= lr*grads 即 w = w - lr*grads
    print("After %s epoch,w is %f,loss is %f" % (epoch, w.numpy(), loss))

# lr初始值：0.2   请自改学习率  0.001  0.999 看收敛过程
# 最终目的：找到 loss 最小 即 w = -1 的最优参数w


<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=100.0>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=90.0>
After 0 epoch,w is -301374.812500,loss is 68591520.000000
After 1 epoch,w is 10949052753510400.000000,loss is 8249394870992007856128.000000
After 2 epoch,w is -inf,loss is inf
After 3 epoch,w is nan,loss is inf
After 4 epoch,w is nan,loss is nan
After 5 epoch,w is nan,loss is nan
After 6 epoch,w is nan,loss is nan
After 7 epoch,w is nan,loss is nan
After 8 epoch,w is nan,loss is nan
After 9 epoch,w is nan,loss is nan
After 10 epoch,w is nan,loss is nan
After 11 epoch,w is nan,loss is nan
After 12 epoch,w is nan,loss is nan
After 13 epoch,w is nan,loss is nan
After 14 epoch,w is nan,loss is nan
After 15 epoch,w is nan,loss is nan
After 16 epoch,w is nan,loss is nan
After 17 epoch,w is nan,loss is nan
After 18 epoch,w is nan,loss is nan
After 19 epoch,w is nan,loss is nan
After 20 epoch,w is nan,loss is nan
After 21 epoch,w is nan,loss is nan
After 22 epoch,w is na

In [2]:
import tensorflow as tf 

state = tf.Variable(0,name='counter')
# print(dir(state))
print(state)
# print(state.value())
# one = tf.constant(1)

# new_value = tf.add(state,one)
# update = tf.assign(state,new_value)

# init = tf.initialize_all_variables()

# with tf.Session() as sess:
#     sess.run(init)
#     for step in range(3):
#         sess.run(update)
#         print(sess.run(state))

<tf.Variable 'counter:0' shape=() dtype=int32, numpy=0>


In [3]:
import tensorflow as tf

tensorflow_version = tf.__version__
gpu_available = tf.test.is_gpu_available()

print("tensorflow version:", tensorflow_version, "\tGPU available:", gpu_available)

a = tf.constant([1.0, 2.0], name="a")
b = tf.constant([1.0, 2.0], name="b")
result = tf.add(a, b, name="add")
print(result)


tensorflow version: 2.1.0 	GPU available: False
tf.Tensor([2. 4.], shape=(2,), dtype=float32)


In [9]:
y_train=tf.constant([1,3,0])
a = tf.one_hot(y_train, depth=6)
print(a)

tf.Tensor(
[[0. 1. 0.]
 [0. 0. 0.]
 [1. 0. 0.]], shape=(3, 3), dtype=float32)


In [6]:
import tensorflow as tf
x = tf.constant([[1.,1.],[1.,-1.]])
y = tf.constant([[1.],[2.]])
print(tf.matmul(x,y))

InvalidArgumentError: Matrix size-incompatible: In[0]: [2,2], In[1]: [1,2] [Op:MatMul] name: MatMul/